---
version: "3.9"

services:
  app:
    image: tolseone/item-service:latest
    container_name: ps-backend
    ports:
      - 44044:44044
    depends_on:
      - postgres
    networks:
      - postgres
    environment:
      POSTGRES_PASSWORD: postgres
    
  postgres:
    container_name: ps-psql
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./ps-psql-data:/var/lib/postgresql/data
      # - ./migrations:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mymail.ru
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - 8080:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: